### ISSUE TITLE
Options not working reliably yet

### ISSUE THREAD

**Issue by VooDisss** [dirtdigger/fleur_de_cali#3]
calistar.py crashes when decreasing "thickness" setting from 4 to less. 

I suggest implementing some restrictions if those settings depend on each other so much that the script crashes. So the user can not change something beyond a dynamic limit, before launching the script... (may be difficult to implement interactive script)

**Comment by dirtdigger** [comment]
I can't reproduce. The latest version works fine if I set thickness down as low as 2.0 with no errors. What other settings have you tweaked?

The very maximum that the chamfer and pa variables cannot be more than half the size of the thickness, otherwise you'll cut away vital geometry. There are probably other constraints that arises from the top/bottom chamfer, but the geometry there is somewhat complex and there may not be a closed for solution for that constraint.

**Comment by VooDisss** [comment]
Okay, I got it working, I think this was due to thickness being too small in relation to chamfer... have to either decrease or disable the chamfering function...

I will close the issue, once I successfully test disabling or lowering chamfer and reducing thickness settings
